# Generated by Django 3.0.8 on 2020-07-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200729_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
    ]
