# Generated by Django 3.0.8 on 2020-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200729_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='des',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
