# Generated by Django 3.0.8 on 2020-08-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200804_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slider_description', models.TextField(blank=True, default=None, null=True)),
                ('slider_image', models.ImageField(blank=True, default=None, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Product')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_images/'),
        ),
    ]
